### PR TITLE
💖 v1.0.0

### PR DESCRIPTION
**Pull request by cuire**
- [x] #21 
- [x] #23
- [x] Merge 0.3.0 and 0.4.0 changes
- [x] Two way items binding with new api???
- [x] Events
- [x] Dispatch event when compressing or pushing items
- [x] Throw an error when `compress !== 'none'` and itemSize.height is not provided 
- [x] New readme
- [x] Update repls
- [x] Release with blackjack and big bang 🍾💥

### CODE REVIEW

**Comment by fabiot21** [comment]
will 1.0 be using svelte 4?

**Comment by cuire** [comment]
> will 1.0 be using svelte 4?

I think the project can support both svelte 3 and svelte 4, since its not rely on any breaking changes

**Comment by fabiot21** [comment]
@cuire is there anything i can help you with?

**Comment by cuire** [comment]
> @cuire is there anything i can help you with?

New api and griditem customization api is ready. If you want to help, you can work on transferring new functionality from #35 and #27. Send PR to `refactoring` branch.

**Comment by fabiot21** [comment]
> > @cuire is there anything i can help you with?
> 
> New api and griditem customization api is ready. If you want to help, you can work on transferring new functionality from #35 and #27. Send PR to `refactoring` branch.

Is it possible to do a rebase or merge from main?

**Comment by cuire** [comment]
> > > @cuire is there anything i can help you with?
> > 
> > New api and griditem customization api is ready. If you want to help, you can work on transferring new functionality from #35 and #27. Send PR to `refactoring` branch.
> 
> Is it possible to do a rebase or merge from main? or this new api is breaking the new functions?

There a lot of internal breaking points. Actually Ill do it myself within next week. Ty for your support ❤️

**Comment by fabiot21** [comment]
Got it @cuire . I sent a PR (#37) 😄. Hope it helps

**Comment by fabiot21** [comment]
What are your thoughts on setting a default value for `itemSize.height` and `itemSize.width` in case `rows=0` or `cols=0`? To avoid unexpected errors / behaviours.

**Comment by cuire** [comment]
> What are your thoughts on setting a default value for `itemSize.height` and `itemSize.width` in case `rows=0` or `cols=0`? To avoid unexpected errors / behaviours.

I don't really like this. That is in fact unexpected behaviour, that requires extra attention from devs. I think simple error throwing is more suted here.

**Comment by fabiot21** [comment]
👏🚀

**Pull request merged**
